# Generated by Django 4.2.5 on 2023-09-25 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_artical_reporter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
