# Generated by Django 4.2.5 on 2023-09-27 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_fileuplodemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileUplodeModel",
        ),
    ]
